; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize

; 1. 开启多线程并行编译 (根据你的 CPU 核心数，-j8 代表 8 线程)
build_flags = 
 ;   -j 8
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    kosme/arduinoFFT @ ^1.5.6
    knolleary/PubSubClient @ ^2.8

; --- 核心加速配置 ---


; 2. 启用编译缓存 (极力推荐)
; 第一次编译后，后续编译只会处理修改过的文件，未改动的库文件直接调用缓存
build_cache_dir = .cache

; 3. 优化编译增量逻辑
; 确保 PlatformIO 只检查文件的 MD5 变化，而不是每次都扫描所有依赖
lib_ldf_mode = chain